language: java
jdk: openjdk8
before_install:
- openssl aes-256-cbc -K $encrypted_7d07226627da_key -iv $encrypted_7d07226627da_iv
  -in firebase-sdk-key.json.enc -out firebase-sdk-key.json -d
- curl -sL https://firebase.tools | bash
script: firebase emulators:exec --only auth --project turma-de-elite-app './gradlew test'
deploy:
  provider: heroku
  strategy: git
  api_key:
    secure: kvSlDjM6oGtOzHAOJ8eWcD+58h32rYMRlbSfM0dC7wEDVXvIFB0EVsbvCtoRFdqvdSB0zzsgUMAPXIcrexsoSQgcJlTIN6p9r+XHhRFYmJDqbiZmogtnPyKWRoHzkDBa9eoKBr4OEeBRrCDMzYhrLOVDwjk+iqPkbh5Iw8V7Zhb3whUoYwXEkcYdAtgla0BGfl+ItndHR37y8eHRpzCC1Z/cA6WuwW1Tr8lkop20gBI9COrnjpAzZuqAYoMzxyp34Pu5CPdR0NoYGvg3Y48dMOicQfo74KOS0Y4iy/yqSCclrWJyv4c14ikZprZrexsrDk+CzI8/3tqUMZx+5akqwcMhwuK7bHIMHtraZ4W0A8/FpnXtTWGcyjvrIuA03vup78c/kobMOc+U4nU25oThsWwiKfmtyQpf59asPFGSZc6H9cBvPtdgFa358mdaLSid3YtMtJ4DI51kDLdiv2+38v6csRD3IOQVdUL9N4qsaQzTIC5q0+yJaZxvDut1B6kd9OiFMDf3rk3zus8AYATiRQqWSQZrlykyiktJegasUSQOgEMfckuYndIbb0jYVwSYh0DzMp9QuW/uLJyX18cQW3rC88bwo4lKgX22TjCbjJz/2cvhr8g/a7Bh2ON6IzRbEfYJ8UHcN1hs3isBbAJTV5DUIDWxT5FJWiN+d42IeZ0=
  app: turma-de-elite
  on:
    branch: release
    condition: release
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  npm: true
  directories:
  - "$HOME/.cache/firebase"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
env:
  global:
  - secure: NiAKoUS/xQO4tkqlvflAML/npAVFErLGsDT5gamTyFdBFCetuIU0mX2GJedYAWa4fCM1oNs2GOPswBBrrAkkTHop3B83Ko2c8Ce/qJEQUo1n7Cf1hT4czFhjpskZBGbK9z1z1yoWY/0YajxT7WuzRN88H1vQou+Np5qGPE/3mst/ZB7WNDUh9fPvRDRZx4rqh7gmPZA2zqotKi/GbU6LFHcQ1kVyw9pp6uSO7QMkiRQtpS2/+e7pPv87iVqbelgPExV79hbx0wykk6TqsVAosmr/Va9qwduhK/131rxLwlseb3pOTDPNRSZvMvOE7xdvU65NvuZoLso9JjrVmmRb7+s9+cbAMiKMgubavPwWSHKrdU7pBAEeEUWc3MUKZShS4sWTqL7ku3/LXnyHMYa+AFIKdfNhmdQPGRDSeB0bK8AQQsU1cg1t86usfG1AJ0J192xXN8ljhUIVJC/Yk/tZ6yjyvOurpm4HVoGj/qXMmaviAgFbfBOoWg1wikXSckfvg4PdsZIlTIwFQQQtoKw4PnoSUK92C8Va3W5WMPqzRfK/oDv9NzUEqx3sso61KRUEtWbuHOl4Eb5N3wgpExe6OhW5p2tzdHyu5R2BPcNOBVJICfxRnz3KD/2BmXxXmw2FJh5JULxY+ZSBJT/QdtrUyUK1XkRTcRZdEEk5Mq7Euks=
  - secure: ePkWctZauFHf9PGesmcXdLilBwnMh9rL8xThbkwxiVrB5ITPDBjnJxZ3P9WIPeekPg6x03mmHfn9YTVos96x7egbNUifvJP7MjOR7ueTTyMwGgOYXGXO+BvzeY+o9ZoYyoxtnlIRyW3lBdQKcuhP9pS3k64oEcbQ18xPS0UPdA0aY0oYXCdhOzkqzu11arWxSZGBxhs/GVH0IToJkN7CyKI26yJenhONHFGRzMy35U4r6xFJD/kYyICX12curczLaU/6zfyYF3BWKTL3pI60C5hyNi9Ns5ki0O1ny3wffupb8AocK6dGVT9nJ1eiiZ9CWy7PLQCK8RCfaEEJICFd5Wkkm6jbLJ9GxhxXSAid3KCjNJFOdy96ZFqink7ksvrIpsGDYERB3mWKoMqMAjxyBH5IJsfgi0KwkhqZt/M6qNp1Nq/FBpeAZ87gTCQl9Ivaj6eQa707rStRphKvQGV7jJy33sOZvLD644vXyCUp+U0OqSFY47VjKCuTHFeWbryZnDmTygGwy/MKWsqq42gpboPTkfShRcMf3mrUoWnivANhs68QSjsTwWYk2iMo0XEiMEQjjfGVpNSVHfSIGwSoAuNdRf05vnAs6xsu7dgPehI1yE3slL6Gt5NM2NlrpS7oDboXIUqnhwdT5rW2bPQqcFZXPYMHa7eCydBEYQyRYPc=
  - secure: geEmhKjh9alVTtVTzdNoeCTn9g0kem5hMdIwviV4MMrbyHahbIYbHjsqtx0OkxrBPg5I9Rj5A53YDejQU4GoxOCEUaQyoytceH244F+KmS4r5+SiaaPd/iJnKr1Wct6QQpmA8k2NDVPKV0VZ/GrBhvrVcLOpqHqELTIMD5OAMXDX37RcnwsLFSI/7FWnYInJ73lSPzJHLRxaw7hW50RWgnyhLfwhAJNO0r12oRHL9w2B0tPaZHjRio53rvNbrPz5yI83qQfuZoVDVnYpcx5/3ZtMp+NxA3OTF0mx1US0R8eFJz+HByGKJYVnS2ykWmk1eS/i2YB+rDfCiXenMEwJuuoK56g43LG6vI64fs09w6Uvs/nZbb2XZxCBjdxXAhtLGTwSA+WmjfVkhB5vcnhbreCJKBoBVTo4fM9B6Byvekaz+4ce8pUYGtUEeMcZElFRy11+mhBIq6mxxrKVtKIRJMOX3eUk4v87mMY/5ffaqqJItOVla7A/hfOEXdGY0PSsH1rirwBXB51MmGlSEMx/5dywUNt13burMW8dAfmkyjnS3nhJEUVfqgh0mTuJW3RLyX3hiye1vcMjgdPrC4S2hQEiAE0yzARRE/Mfoy0cKDh4Orna4SnThAXNf7nDqNFYmP/YqIvCo/69dhMMByzBxaSFOssA5mrk7oheGbtJ35Y=
