language: java
jdk: openjdk8
script: "./gradlew test"
deploy:
  provider: heroku
  strategy: git
  api_key:
    secure: kvSlDjM6oGtOzHAOJ8eWcD+58h32rYMRlbSfM0dC7wEDVXvIFB0EVsbvCtoRFdqvdSB0zzsgUMAPXIcrexsoSQgcJlTIN6p9r+XHhRFYmJDqbiZmogtnPyKWRoHzkDBa9eoKBr4OEeBRrCDMzYhrLOVDwjk+iqPkbh5Iw8V7Zhb3whUoYwXEkcYdAtgla0BGfl+ItndHR37y8eHRpzCC1Z/cA6WuwW1Tr8lkop20gBI9COrnjpAzZuqAYoMzxyp34Pu5CPdR0NoYGvg3Y48dMOicQfo74KOS0Y4iy/yqSCclrWJyv4c14ikZprZrexsrDk+CzI8/3tqUMZx+5akqwcMhwuK7bHIMHtraZ4W0A8/FpnXtTWGcyjvrIuA03vup78c/kobMOc+U4nU25oThsWwiKfmtyQpf59asPFGSZc6H9cBvPtdgFa358mdaLSid3YtMtJ4DI51kDLdiv2+38v6csRD3IOQVdUL9N4qsaQzTIC5q0+yJaZxvDut1B6kd9OiFMDf3rk3zus8AYATiRQqWSQZrlykyiktJegasUSQOgEMfckuYndIbb0jYVwSYh0DzMp9QuW/uLJyX18cQW3rC88bwo4lKgX22TjCbjJz/2cvhr8g/a7Bh2ON6IzRbEfYJ8UHcN1hs3isBbAJTV5DUIDWxT5FJWiN+d42IeZ0=
  app: turma-de-elite
  on:
    branch: release
    condition: release
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"