language: java
jdk: openjdk8
before_install:
- openssl aes-256-cbc -K $encrypted_7d07226627da_key -iv $encrypted_7d07226627da_iv
  -in firebase-sdk-key.json.enc -out firebase-sdk-key.json -d
- curl -sL https://firebase.tools | bash
script: firebase emulators:exec --project turma-de-elite-app ./gradlew test
deploy:
  provider: heroku
  strategy: git
  api_key:
    secure: kvSlDjM6oGtOzHAOJ8eWcD+58h32rYMRlbSfM0dC7wEDVXvIFB0EVsbvCtoRFdqvdSB0zzsgUMAPXIcrexsoSQgcJlTIN6p9r+XHhRFYmJDqbiZmogtnPyKWRoHzkDBa9eoKBr4OEeBRrCDMzYhrLOVDwjk+iqPkbh5Iw8V7Zhb3whUoYwXEkcYdAtgla0BGfl+ItndHR37y8eHRpzCC1Z/cA6WuwW1Tr8lkop20gBI9COrnjpAzZuqAYoMzxyp34Pu5CPdR0NoYGvg3Y48dMOicQfo74KOS0Y4iy/yqSCclrWJyv4c14ikZprZrexsrDk+CzI8/3tqUMZx+5akqwcMhwuK7bHIMHtraZ4W0A8/FpnXtTWGcyjvrIuA03vup78c/kobMOc+U4nU25oThsWwiKfmtyQpf59asPFGSZc6H9cBvPtdgFa358mdaLSid3YtMtJ4DI51kDLdiv2+38v6csRD3IOQVdUL9N4qsaQzTIC5q0+yJaZxvDut1B6kd9OiFMDf3rk3zus8AYATiRQqWSQZrlykyiktJegasUSQOgEMfckuYndIbb0jYVwSYh0DzMp9QuW/uLJyX18cQW3rC88bwo4lKgX22TjCbjJz/2cvhr8g/a7Bh2ON6IzRbEfYJ8UHcN1hs3isBbAJTV5DUIDWxT5FJWiN+d42IeZ0=
  app: turma-de-elite
  on:
    branch: release
    condition: release
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  npm: true
  directories:
  - "$HOME/.cache/firebase"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
env:
  global:
  - secure: TC9lqC0CJSbu7aUPJLDfbB/O59i/Ap5ydAizzipZecXOLvmJ3z9PEytUtETO2oIhwXUyPrYKxtlwvLVeeB8hDK1Oxct2y5MY0yF0kc5OI6w/6frLRxXmc07Cyds2mQEnJrpd6I7EuPihkdOl33BP27WsamyApF2rWADdXk+hUUU2OVFmOIR1NLr/TlqXVRoBS7f4tKeI5VOGt/DSuTiQD4gYO8TlWBykC0dlgKIGCJwp7QRiZZ4l62VuPeVuJ2dHNgH9plq+Z0stho1rCl+TLC/RuEN0//E91S1kHjcNu7oYaaE3cJYNHhj4tpuOku9bkXm7Wjk12kDnxuI0E6P4yFpwiIqpT7CTvTLXknVMXl+u2LTuq/WrctEXPuIe5I4hqd94p2FX/FOo4f17mmeVUdlcqNT5WvnsuoyyONqh/+0/5TOoOe6oKpj5Rc1aNZGbKiiqKS1zwT+goMKxtx/kXzrqQP3QU6A8zHplGpjPzy2mu/WHY53DukrgW2VehXQhDz4NHDkqTA/bsPGqvarMu+VWWDdtPImMIbcqfTdgIlm5XMQ+LEg7TGKg/5cIpmzVYLBs2cLTmsdsWLoVeIpStZS3gCpU+duk/5FObWHZoRn1+f6CLCe6aWcy/BCHK7KlQWiBs12uIvUlqu5V4zDJoX76odF8YLXxFjZnZLhUtNE=
  - secure: fdjB6wjpvzq+yYuLe93ot34fJn8tsjo/JFdEFqj1OFg9dv8njfJJiBeqYw/l1T0W8cpIMAkxgceCS6537QCu7zUMP+nI00THL1HeXU8sdNKvqWHvOzo2DEmJTTDckyQlTc7t+dbpA6kVznPyktQp5AMidBRrNQk3o/I5Lda+6ImZZE3uyXiiXj2qdu7/aSVDTo5Bz7XNRRmERyR2bePFHam0g4rnExfNGNXXQtdPMfVNDdGebaBZIX1pA38dGZGlJpoi7DYywjap6IohrjCVvYybVRtFOc1wMR4nyiUjkOg5RGt2CCVbLzRwsNhQf8C0T9qo3XFmKBus8yqLetl6TSlNinf6o0MG3CsmC5+LdEYk4U1nuayxsHGQ+6XeLXM3zujzpHE/TG554wL0Hq/cJfWpw0Fq5iuNrPb6EWnqxS2oLyFjb35WN95LMCWdCRVxLbAAPF0mMJDB5fNnBfAby+k8g5JOQXm0mG+hAEvojMysubmsIsUucojaGkUHf5tGCjtxSmsH1SQ5I7YC/sstio6y0Vk76tkhVwy1AXKjVHLcrnZl+c/lZF5u7C1mcIXdvHYrtyj+38y6WeGPiMPFi00XE7Wxeah4i3kEe9U7ZApRYoOwvLhppi4+FxPO3xaeMnY6YDw1AL0JSIBVLLJgP6vEqUg9n/O1RU5pqOMZzxA=
  - secure: VpR9TKVUqfKsUzXmWt7ptg5YuJQ6t8TxUJ8TYP8qinAJM3lr+AveGICqRbLUOcYFnCdj5//HEdm21IRoZeND/rjGekAJ6NZJ8oQ7brgmfwHtqhP+GPptXMq/6LcEZecY8EdigxbRqhay5J4eb1bPkDhq+wgP8s676AW4lZy1zc6ZGcyKXlBPQghGDa6FwKRkMhwt8FUcVAq/hnLfI7c+zkVIe+c1jqdoXNgYU1fdZ178HSbmZfgkHV/Ni8rIMHCLcjLKNVVWRsd8kSwLfil6txOSpABRZ8q7o+O8UXpH9N7G6wCuodAl6j/rHGjL/Lrg4A49615GijkQxH3EBOLg6cUv22KMpsf+zf73YO9+C21xooqsw5fjOooMtfTfcxx04wQgwoEDDyHturhd20Vnj8hRpuLHYFjVWPPRashN09KbjGr2e1/z4z2wEW1av04tTAMKsrPn3OqO1P3+UR2drTV62V66JeAUBEL6ZjmFakhtsYb07S0BTlg4Ymna061M5lKXsjPhh30YgwvtkoojD0Ufa3Vio6xrjxOCH1Sbmg5LqlPc2pmruQpNcRXC3WX8LXIril2E4FXhabwRy6aZ1u1J9JgDMLM5Cz4bYksVQ7BaYDTAaZgVD7Nnk9evsv0YZxUt9cbpVLQySKjrzWKis9s3/fWvp4nbtxedJrdNfrE=
